# Generated by Django 4.1.2 on 2022-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role_type",
            field=models.SmallIntegerField(
                choices=[(0, "STUDENT"), (1, "TEACHER"), (2, "ADMIN")], default=0
            ),
        ),
    ]
