[start]
  
  runImage = 'python:3.10.6-slim'

[phases.setup]
  nixPkgs = ["...", "ffmpeg"] # Install the ffmpeg package from Nix
  aptPkgs = ["...", "wget"]   # Install the wget package with apt-get
[phase.name]

[phases.install]
  aptPkgs = ['...',]

    
 

 
    



